# Generated by Django 4.2 on 2023-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Surgeon', 'Surgeon'), ('psychiatrist', 'psychiatrist'), ('neurologist', 'neurologist'), ('general practitioner', 'general practitioner')], max_length=50)),
            ],
        ),
    ]
