# Generated by Django 4.2 on 2023-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
