# Generated by Django 4.2 on 2023-04-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parchi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parchi',
            options={'ordering': ['start_time']},
        ),
        migrations.RenameField(
            model_name='parchi',
            old_name='doctors',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='parchi',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='parchi',
            name='time',
        ),
        migrations.AddField(
            model_name='parchi',
            name='date',
            field=models.DateField(default='', verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parchi',
            name='end_time',
            field=models.TimeField(default=1, verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parchi',
            name='start_time',
            field=models.TimeField(default=2, verbose_name='Start time'),
            preserve_default=False,
        ),
    ]
