# Generated by Django 4.2 on 2023-04-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_parchi_options_rename_doctors_parchi_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parchi',
            options={},
        ),
        migrations.RenameField(
            model_name='parchi',
            old_name='doctor',
            new_name='doctors',
        ),
        migrations.RemoveField(
            model_name='parchi',
            name='date',
        ),
        migrations.RemoveField(
            model_name='parchi',
            name='end_time',
        ),
        migrations.AddField(
            model_name='parchi',
            name='sr_no',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parchi',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
