# Generated by Django 4.2 on 2023-04-21 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_parchi_options_rename_doctor_parchi_doctors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sr_no', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.doctors')),
            ],
        ),
        migrations.DeleteModel(
            name='parchi',
        ),
    ]
