# Generated by Django 4.2 on 2023-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_appointment_delete_parchi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(verbose_name='YYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(verbose_name='YYY-MM-DD'),
        ),
    ]
