# Generated by Django 4.2 on 2023-04-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
    ]
